export default {
    "AL": { name: "Alabama", link: 'http://www.outdooralabama.com/alabama-license-information' },
    "AK": { name: "Alaska", link: 'http://www.adfg.alaska.gov/index.cfm?adfg=hunting.huntingregulations' },
    "AZ": { name: "Arizona", link: 'http://www.azgfd.gov/h_f/hunting_rules.shtml' },
    "AR": { name: "Arkansas", link: 'http://www.agfc.com/hunting/Pages/HuntingRegulations.aspx' },
    "CA": { name: "California", link: 'https://www.wildlife.ca.gov/Regulations' },
    "CO": { name: "Colorado", link: 'http://cpw.state.co.us/thingstodo/Pages/OHVsRegsStatutes.aspx' },
    "CT": { name: "Connecticut", link: 'http://www.ct.gov/deep/site/default.asp' },
    "DE": { name: "Delaware", link: 'http://delcode.delaware.gov/title7/c005/index.shtml' },
    "FL": { name: "Florida", link: 'http://myfwc.com/license/recreational/hunting/' },
    "GA": { name: "Georgia", link: 'http://www.georgiawildlife.com/hunting/regulations' },
    "HI": { name: "Hawaii", link: 'http://dlnr.hawaii.gov/programs/huntered/' },
    "ID": { name: "Idaho", link: 'http://fishandgame.idaho.gov/public/hunt/rules/' },
    "IL": { name: "Illinois", link: 'http://www.dnr.illinois.gov/hunting/Pages/HuntingTrappingDigests.aspx' },
    "IN": { name: "Indiana", link: 'http://www.in.gov/dnr/fishwild/2343.htm' },
    "IA": { name: "Iowa", link: 'http://www.iowadnr.gov/Hunting/HuntingLicensesLaws.aspx' },
    "KS": { name: "Kansas", link: 'http://www.kdwpt.state.ks.us/news/Hunting/Hunting-Regulations' },
    "KY": { name: "Kentucky", link: 'http://fw.ky.gov/Enforcement/Pages/Regulations.aspx' },
    "LA": { name: "Louisiana", link: 'http://www.wlf.la.gov/hunting/regulations' },
    "ME": { name: "Maine", link: 'http://www.maine.gov/ifw/laws_rules/hunting_trapping/hunt_traplaws.htm' },
    "MD": { name: "Maryland", link: 'http://www.dnr.state.md.us/wildlife/index.asp' },
    "MA": { name: "Massachusetts", link: 'http://www.mass.gov/eea/agencies/dfg/dfw/laws-regulations/' },
    "MI": { name: "Michigan", link: 'http://www.michigan.gov/dnr/0,1607,7-153-10366_37141---,00.html' },
    "MN": { name: "Minnesota", link: 'http://www.dnr.state.mn.us/regulations/hunting/index.html' },
    "MS": { name: "Mississippi", link: 'http://www.mdwfp.com/law-enforcement/hunting-rules-regs.aspx' },
    "MO": { name: "Missouri", link: 'http://huntfish.mdc.mo.gov/hunting-trapping/regulations' },
    "MT": { name: "Montana", link: 'http://fwp.mt.gov/hunting/regulations/' },
    "NE": { name: "Nebraska", link: 'http://outdoornebraska.gov/regulations/' },
    "NV": { name: "Nevada", link: 'http://www.ndow.org/laws/' },
    "NH": { name: "New Hampshire", link: 'http://www.wildlife.state.nh.us/legislative/index.html' },
    "NJ": { name: "New Jersey", link: 'http://www.state.nj.us/dep/fgw/njregs.htm' },
    "NM": { name: "New Mexico", link: 'http://www.wildlife.state.nm.us/hunting/general-rules/' },
    "NY": { name: "New York", link: 'http://www.dec.ny.gov/outdoor/28182.html' },
    "NC": { name: "North Carolina", link: 'http://www.ncwildlife.org/Hunting/LawsSafety.aspx' },
    "ND": { name: "North Dakota", link: 'https://gf.nd.gov/hunting/regulations' },
    "OH": { name: "Ohio", link: 'http://wildlife.ohiodnr.gov/huntingandtrappingregulations' },
    "OK": { name: "Oklahoma", link: 'http://www.wildlifedepartment.com/laws_regs.htm' },
    "OR": { name: "Oregon", link: 'http://www.dfw.state.or.us/resources/hunting/index.asp#Rules' },
    "PA": { name: "Pennsylvania", link: 'http://www.pgc.pa.gov/HuntTrap/Law/Pages/default.aspx' },
    "RI": { name: "Rhode Island", link: 'http://www.dem.ri.gov/documents/regulations/index.php#hunting-fishing' },
    "SC": { name: "South Carolina", link: 'http://www.dnr.sc.gov/regulations.html' },
    "SD": { name: "South Dakota", link: 'http://gfp.sd.gov/hunting/regulations/default.aspx' },
    "TN": { name: "Tennessee", link: 'http://www.tn.gov/twra/article/deer-seasons' },
    "TX": { name: "Texas", link: 'http://tpwd.texas.gov/regulations/outdoor-annual/hunting/' },
    "UT": { name: "Utah", link: 'http://wildlife.utah.gov/hunting-in-utah/guidebooks.html' },
    "VT": { name: "Vermont", link: 'http://www.vtfishandwildlife.com/hunt/hunting_regulations' },
    "VA": { name: "Virginia", link: 'http://www.dgif.virginia.gov/hunting/regulations/' },
    "WA": { name: "Washington", link: 'http://wdfw.wa.gov/hunting/regulations/' },
    "WV": { name: "West Virginia", link: 'http://www.wvdnr.gov/hunting/hunting_regs.shtm' },
    "WI": { name: "Wisconsin", link: 'http://dnr.wi.gov/topic/hunt/regulations.html' },
    "WY": { name: "Wyoming", link: 'https://wgfd.wyo.gov/regulations' }
};